
name: advent-of-code-2k22 CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

jobs:
  advent-of-code-2k22-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl git sudo
      - name: Install Docker
        run: |
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          sudo echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - name: Install cqfd
        run: |
          git clone https://github.com/savoirfairelinux/cqfd.git
          cd cqfd
          sudo make install
      - name: Initialize cqfd
        run: |
          cqfd init
      - name: Install googletest
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          git checkout v1.17.0
      - name: Build all days with tests
        run: |
          cqfd -b test
      - name: Run tests
        run: |
          cqfd run bin/tests
      - name: Run days
        run: |
          cqfd run bin/day1
          cqfd run bin/day2
          cqfd run bin/day3
